### ISSUE TITLE
Casts in muapi.h, please

### ISSUE THREAD

**Issue by eliotmoss** [microvm/microvm-spec#1]
Things like MU_BINOP_ADD should have the cast to MuBinOptr, e.g.:
# define MU_BINOP_ADD ((MuBinOptr)0x01)

(This is the consensus of the UMass team + Tony)

**Comment by wks** [comment]
Good idea. This will force them to have the appropriate sizes and signedness.

Fixed in 831315bd6de4bcd56c7f7f7e1d11fc05444d94e6
